// backend/jobs/scheduledReports.js
// Cron-based scheduled report runner.
// Reports marked isScheduled=true are run automatically and emailed.
//
// Setup: call initScheduler() once from server.js after DB connects.
//
// Requires: npm install node-cron nodemailer exceljs json2csv

const cron       = require('node-cron');
const nodemailer = require('nodemailer');
const ExcelJS    = require('exceljs');
const { Parser: CsvParser } = require('json2csv');
const Report     = require('../models/Report');
const User       = require('../models/User');
const { buildPipeline } = require('../services/reportBuilderService');

// ─── Email transporter (reuse existing .env vars) ─────────────────────────────
function getTransporter() {
  return nodemailer.createTransport({
    host: process.env.EMAIL_HOST,
    port: Number(process.env.EMAIL_PORT) || 587,
    secure: false,
    auth: {
      user: process.env.EMAIL_USER,
      pass: process.env.EMAIL_PASS,
    },
  });
}

// ─── Build Excel buffer for email attachment ──────────────────────────────────
async function buildExcelBuffer(rows, fields, reportName) {
  const wb = new ExcelJS.Workbook();
  const ws = wb.addWorksheet(reportName);
  const cols = fields?.length
    ? fields
    : Object.keys(rows[0] || {}).filter(k => k !== '_id' && k !== '__v');

  ws.addRow(cols.map(c => c.replace(/([A-Z])/g, ' $1').replace(/^./, s => s.toUpperCase())));
  ws.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  ws.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FF1E40AF' } };

  rows.forEach((row, i) => {
    const values = cols.map(c => {
      const v = row[c];
      if (v === null || v === undefined) return '';
      if (typeof v === 'object') return JSON.stringify(v);
      return v;
    });
    const r = ws.addRow(values);
    if (i % 2 === 0) r.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF1F5F9' } };
  });
  ws.columns.forEach(col => { col.width = 18; });

  return wb.xlsx.writeBuffer();
}

// ─── Run a single scheduled report and email it ───────────────────────────────
async function runAndEmail(report) {
  try {
    const { model, pipeline } = buildPipeline({
      module:   report.module,
      fields:   report.fields,
      filters:  report.filters,
      groupBy:  report.groupBy,
      sortBy:   report.sortBy,
      schoolId: report.school,
    });
    pipeline.push({ $limit: 5000 });
    const rows = await model.aggregate(pipeline);

    if (!rows.length) {
      console.log(`[ScheduledReport] "${report.name}" — no data, skipping email`);
      return;
    }

    // Find report creator to email
    const creator = await User.findById(report.createdBy);
    if (!creator?.email) return;

    // Build XLSX attachment
    const buffer   = await buildExcelBuffer(rows, report.fields, report.name);
    const filename  = `${report.name.replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.xlsx`;

    const transporter = getTransporter();
    await transporter.sendMail({
      from:    `EduCore Reports <${process.env.EMAIL_USER}>`,
      to:      creator.email,
      subject: `Scheduled Report: ${report.name}`,
      html: `
        <div style="font-family:sans-serif;max-width:560px">
          <h2 style="color:#1D4ED8">📊 ${report.name}</h2>
          <p>Your scheduled report is ready. Please find the <strong>${rows.length} rows</strong> attached as an Excel file.</p>
          <p style="color:#6B7280;font-size:13px">
            Module: ${report.module} &nbsp;|&nbsp;
            Generated: ${new Date().toLocaleString('en-IN')}
          </p>
          <p style="font-size:12px;color:#9CA3AF">This report was automatically generated by EduCore. To manage scheduled reports, log in to the Reports module.</p>
        </div>
      `,
      attachments: [{ filename, content: buffer }],
    });

    console.log(`[ScheduledReport] "${report.name}" emailed to ${creator.email} (${rows.length} rows)`);

    // Log to downloadHistory
    report.downloadHistory.unshift({ exportedBy: report.createdBy, format: 'xlsx', rowCount: rows.length });
    if (report.downloadHistory.length > 20) report.downloadHistory.pop();
    await report.save();

  } catch (err) {
    console.error(`[ScheduledReport] Error running "${report.name}":`, err.message);
  }
}

// ─── Scheduler init — call once from server.js ────────────────────────────────
exports.initScheduler = function() {
  if (!process.env.EMAIL_HOST || !process.env.EMAIL_USER) {
    console.log('[ScheduledReport] Email not configured — scheduler disabled');
    return;
  }

  // Daily reports — every day at 6:00 AM
  cron.schedule('0 6 * * *', async () => {
    console.log('[ScheduledReport] Running daily reports...');
    const reports = await Report.find({ scheduleFrequency: 'daily' });
    for (const r of reports) await runAndEmail(r);
  });

  // Weekly reports — every Monday at 6:30 AM
  cron.schedule('30 6 * * 1', async () => {
    console.log('[ScheduledReport] Running weekly reports...');
    const reports = await Report.find({ scheduleFrequency: 'weekly' });
    for (const r of reports) await runAndEmail(r);
  });

  // Monthly reports — 1st of every month at 7:00 AM
  cron.schedule('0 7 1 * *', async () => {
    console.log('[ScheduledReport] Running monthly reports...');
    const reports = await Report.find({ scheduleFrequency: 'monthly' });
    for (const r of reports) await runAndEmail(r);
  });

  console.log('[ScheduledReport] Scheduler initialized ✓');
};