// backend/models/Timetable.js
// Replaces the basic TimetableSchema in models/index.js
// Drop-in: exports same model name "Timetable"

const mongoose = require('mongoose');

// ── Period sub-document ───────────────────────────────────────────────────────
const PeriodSchema = new mongoose.Schema({
  periodNumber: { type: Number, required: true },        // 1–8
  subject:      { type: mongoose.Schema.Types.ObjectId, ref: 'Subject' },
  teacher:      { type: mongoose.Schema.Types.ObjectId, ref: 'Teacher' },
  startTime:    { type: String, required: true },        // "09:00"
  endTime:      { type: String, required: true },        // "09:45"
  room:         { type: String, default: '' },
  type: {
    type: String,
    enum: ['lecture', 'lab', 'break', 'lunch', 'free', 'assembly'],
    default: 'lecture',
  },
  // Temporary substitution — cleared when original teacher returns
  substitute: {
    teacher:    { type: mongoose.Schema.Types.ObjectId, ref: 'Teacher' },
    reason:     String,
    date:       Date,       // specific date this sub applies (null = permanent)
    assignedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    assignedAt: { type: Date },
  },
  color: { type: String, default: '' }, // hex for frontend display
}, { _id: true });

// ── Day schedule sub-document ─────────────────────────────────────────────────
const DayScheduleSchema = new mongoose.Schema({
  day: {
    type: String,
    required: true,
    enum: ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
  },
  periods: [PeriodSchema],
}, { _id: false });

// ── Main Timetable document ───────────────────────────────────────────────────
const TimetableSchema = new mongoose.Schema({
  class:   { type: mongoose.Schema.Types.ObjectId, ref: 'Class',  required: true },
  school:  { type: mongoose.Schema.Types.ObjectId, ref: 'School', required: true },

  // Versioning — multiple timetables per class, one isActive at a time
  version:     { type: String, default: 'v1', trim: true },       // "v1", "Exam Timetable"
  label:       { type: String, default: 'Main Timetable', trim: true },
  isActive:    { type: Boolean, default: true },                   // currently in use

  // Academic term this timetable covers
  academicYear: { type: String, default: () => {
    const y = new Date().getFullYear();
    return `${y}-${y + 1}`;
  }},

  schedule: [DayScheduleSchema],

  // Auto-generation metadata
  isAutoGenerated: { type: Boolean, default: false },
  generationConfig: {
    periodsPerDay:      { type: Number, default: 8 },
    workingDays:        [String],
    subjectsPerWeek:    { type: mongoose.Schema.Types.Mixed, default: {} }, // { subjectId: 5 }
    breakAfterPeriod:   { type: Number, default: 4 },
    lunchAfterPeriod:   { type: Number, default: 5 },
    breakDuration:      { type: String, default: '15' },           // minutes
    lunchDuration:      { type: String, default: '30' },
    startTime:          { type: String, default: '09:00' },
    periodDuration:     { type: Number, default: 45 },             // minutes
  },

  createdBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  updatedBy:  { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  createdAt:  { type: Date, default: Date.now },
  updatedAt:  { type: Date, default: Date.now },
});

TimetableSchema.pre('save', function(next) {
  this.updatedAt = Date.now();
  next();
});

// Index: fast lookup by class + school + isActive
TimetableSchema.index({ class: 1, school: 1, isActive: 1 });
TimetableSchema.index({ school: 1, version: 1 });

// When one version is activated, deactivate others for same class (handled in controller)
module.exports = mongoose.models.Timetable || mongoose.model('Timetable', TimetableSchema);